import{a as h,S,i as c}from"./assets/vendor-527658dd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const r of a.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();async function f(s,t,o){const E=`https://pixabay.com/api/?key=42589869-a6a3b8d1c8a23a9a4a19ea254&q=${s}&image_type=photo&orientation=horizontal&safesearch=${!0}&per_page=${t}&page=${o}`;return(await h.get(E)).data}function y(s){return document.querySelector(".gallery"),s.map(({webformatURL:t,largeImageURL:o,tags:i,likes:e,views:a,comments:r,downloads:g})=>`<li class="gallery-item">
      <a href="${o}" class="gallery-link" data-lightbox="gallery">
        <img class="gallery-image"
         src="${t}"
         alt="${i}"/>
         <div class="gallery-text">
        <p> <span class="parameter-name">Likes:</span> <span class="likes-value">${e}</span> </p>
        <p><span class="parameter-name">Views:</span> <span class="likes-value">${a}</span></p>
        <p><span class="parameter-name">Comments:</span> <span class="likes-value">${r}</span></p>
        <p><span class="parameter-name">Downloads:</span> <span class="likes-value">${g}</span></p>
        </div>
      </a>
    </li>`).join("")}h.defaults.baseURL="https://pixabay.com/api/";const b=document.querySelector(".btn-section"),v=document.querySelector("#data-search");document.querySelector("[data-start]");const d=document.querySelector(".gallery"),m=document.querySelector(".loader"),n=document.querySelector(".load-more-btn"),L=new S(".gallery a",{captionsData:"alt",captionDelay:250});let l=1;const p=15;let u="";b.addEventListener("submit",I);n.addEventListener("click",A);async function I(s){if(s.preventDefault(),d.innerHTML="",u=await v.value.trim(),!u){c.warning({title:"Warning",message:"Please enter a search term."}),d.innerHTML="";return}l=1,m.classList.remove("is-hidden");try{const t=await f(u,p,l);t.hits.length===0?(n.classList.add("is-hidden"),c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"})):(d.innerHTML=y(t.hits),L.refresh(),n.classList.remove("is-hidden"),t.hits.length<15&&n.classList.add("is-hidden"))}catch(t){console.error("Error fetching images:",t),c.error({title:"Error",message:"An error occurred while fetching images."})}finally{m.classList.add("is-hidden")}}function $(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}async function A(){m.classList.add("is-hidden"),l+=1;try{const s=await f(u,p,l),t=Math.ceil(s.totalHits/p);d.insertAdjacentHTML("beforeend",y(s.hits)),$(),L.refresh(),t===l?(n.classList.add("is-hidden"),c.info({title:"Info",message:"We are sorry, but you have reached the end of search results."})):n.classList.remove("is-hidden")}catch(s){console.error("Error fetching more images:",s)}finally{m.classList.add("is-hidden")}}
//# sourceMappingURL=commonHelpers.js.map
